apiVersion: v1
kind: Service
metadata:
  labels:
    run: dprive-nginx-bind
  name: dprive-nginx-bind
spec:
  type: LoadBalancer
  loadBalancerIP: 104.196.153.172
  ports:
  - name: domain-s
    protocol: TCP
    port: 853
    targetPort: 853
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    run: dprive-nginx-bind

